### ISSUE TITLE
Name params in methods

### ISSUE THREAD

**Issue by leenorshn** [lucdotdev/hover_ussd#3]
Il serait mieux de transformer la method ici sendUssd en avec des parametres plus parlant. par exemple 
` _hoverUssd.sendUssd("c6e45e62", {"price": "4000"});`
soit transformer en
 `_hoverUssd.sendUssd(actionId:"c6e45e62", {"price": "4000"});`
thanks a lot.

**Comment by lucdotdev** [comment]
Merci pour votre demande, elle sera pris en compte et viendras dans la prochaine version 😊
